<template>
	<section class="hero is-info is-fullheight">
	  <div class="hero-head">
	    <nav class="navbar">
	      <div class="container">
	        <div class="navbar-brand">
	          <a class="navbar-item">
	            <div>
	            	<h1 class="title" 
	            		style='color:rgb(255, 255, 255)'>Fast-DetectGPT</h1>
	            </div>
	          </a>
	          <span class="navbar-burger" data-target="navbarMenuHeroB">
	            <span></span>
	            <span></span>
	            <span></span>
	          </span>
	        </div>
	        <div id="navbarMenuHeroB" class="navbar-menu">
	          <div class="navbar-end">
	            <a class="navbar-item is-active">
	              Home
	            </a>
	            <a class="navbar-item">
	              Examples
	            </a>
	            <a class="navbar-item">
	              Documentation
	            </a>
	          </div>
			  <span class="navbar-item">
              <a class="button is-info is-inverted" href="https://github.com/baoguangsheng/fast-detect-gpt">
                <span class="icon">
				  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
                  <i class="fab fa-github"></i>
                </span>
                <span>Github</span>
              </a>
            </span>
	        </div>
	      </div>
	    </nav>
	  </div>
	
	  <div class="hero-body">
	    <div class="container has-text-lefted">
	      <p class="title">
	         Welcome to the Fast-DetectGPT!
	      </p>
	      <p class="subtitle">
			Fast-DetectGPT requires no training and directly uses open-source small language models to detect text content generated by various large language models such as ChatGPT and GPT-4.
			<br><br>
			It boosts the detection speed by 340 times and enhances the detection accuracy by 75% upon DetectGPT, and it outperforms the commercial GPTZero on detection of ChatGPT and GPT-4 generations.
	        <br><br>
			Now you can click the button below to try it!
			<br>
	      </p>
		  <router-link :to="{name:'show'}">
		  	<b-button type="is-primary is-info" inverted outlined>Try it Now →</b-button>
		  </router-link>
	    </div>
	  </div>
	
	</section>
</template>

<script>
export default {
  name: 'HelloWorld',
  props: {
    msg: String
  },
  methods:{
	// clickMe() {
	//     this.$router.push('/show');
	// }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
::v-deep .subtitle {
    margin-top: -1.25rem;
    width: 1035px;
    padding-left: 300px;
	padding-top: 30px;
}
</style>
